<script setup lang="ts">
import { onMounted, ref } from "vue";
import { fetchAuditEvents, type AuditEvent } from "../api";
const rows = ref<AuditEvent[]>([]); const loading = ref(false); const error = ref(""); const keyword = ref("");
const actorType = ref<"" | "admin" | "employee" | "system">(""); const action = ref(""); const createdRange = ref<[string, string] | []>([]);
const page = ref(1); const pageSize = ref(20);
const total = ref(0);
function dayBoundary(value: string, end: boolean): string { return new Date(`${value}T${end ? "23:59:59.999" : "00:00:00"}`).toISOString(); }
async function load(): Promise<void> { loading.value = true; error.value = ""; try { const result = await fetchAuditEvents({ keyword: keyword.value.trim() || undefined, actorType: actorType.value || undefined, action: action.value.trim() || undefined, createdFrom: createdRange.value[0] ? dayBoundary(createdRange.value[0], false) : undefined, createdTo: createdRange.value[1] ? dayBoundary(createdRange.value[1], true) : undefined, page: page.value, pageSize: pageSize.value }); rows.value = result.items; total.value = result.total; } catch (e) { error.value = (e as Error).message; } finally { loading.value = false; } }
function applyFilters(): void { page.value = 1; void load(); }
function resetFilters(): void { keyword.value = ""; actorType.value = ""; action.value = ""; createdRange.value = []; applyFilters(); }
function changePageSize(): void { page.value = 1; void load(); }
function format(value: string): string { return new Date(value).toLocaleString("zh-CN"); }
onMounted(load);
</script>
<template><main class="page-shell"><section class="page-heading"><div><p>追踪员工档案、令牌、探索保存、正式提交、内容查看和评审操作；日志不包含令牌明文。</p></div></section><el-alert v-if="error" :title="error" type="error" show-icon :closable="false"><template #default><el-button link type="primary" @click="load">重试</el-button></template></el-alert><el-card shadow="never" class="content-card"><div class="filter-row"><el-input v-model="keyword" clearable placeholder="搜索操作者或元数据" style="width: 280px" @keyup.enter="applyFilters" /><el-input v-model="action" clearable placeholder="精确动作名称" style="width: 220px" @keyup.enter="applyFilters" /><el-select v-model="actorType" clearable placeholder="全部操作者类型" style="width: 160px"><el-option label="管理员" value="admin" /><el-option label="员工" value="employee" /><el-option label="系统" value="system" /></el-select><el-date-picker v-model="createdRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" style="width: 250px" /><el-button type="primary" @click="applyFilters">查询</el-button><el-button @click="resetFilters">重置</el-button></div><el-table v-loading="loading" :data="rows" style="width: 100%" empty-text="暂无审计事件"><el-table-column label="时间" width="180"><template #default="{ row }">{{ format(row.createdAt) }}</template></el-table-column><el-table-column prop="action" label="动作" width="220" /><el-table-column label="操作者" width="180"><template #default="{ row }">{{ row.actorName || row.actorType }}</template></el-table-column><el-table-column label="探索/需求" min-width="260"><template #default="{ row }">{{ row.explorationId || row.requirementId || '—' }}</template></el-table-column><el-table-column label="元数据" min-width="360" show-overflow-tooltip><template #default="{ row }">{{ JSON.stringify(row.metadata) }}</template></el-table-column></el-table><el-pagination v-model:current-page="page" v-model:page-size="pageSize" class="table-pagination" :page-sizes="[20, 50, 100]" layout="total, sizes, prev, pager, next" :total="total" @current-change="load" @size-change="changePageSize" /></el-card></main></template>
